GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/607db6f3c5a06b628aa2a370

###

POST http://localhost:3000/contacts/
Content-Type: application/json

{
    "name": "Test Tester",
    "email": "test.tester@gmail.com"
}

###

PATCH http://localhost:3000/contacts/607db6f3c5a06b628aa2a379
Content-Type: application/json

{
    "name": "Testmore"
}

###

DELETE http://localhost:3000/contacts/607f16ba42e66a1180ad3d0c