GET http://localhost:5000/api/members/

###

GET http://localhost:5000/api/members/6

###

POST http://localhost:5000/api/members/
Content-Type: application/json

{
    "name": "Test Member",
    "email": "test.member@gmail.com"
}

###

PUT http://localhost:5000/api/members/1
Content-Type: application/json

{
    "name": "John Doe"
}

###

DELETE http://localhost:5000/api/members/1d263909-921e-43e8-b983-55698aab2916